### ISSUE TITLE
 Code Review 2

### ISSUE THREAD

**Issue by oivaaa** [mcpaulafi/Todotoday#2]
Sovellus on niin hyvällä mallillaan, että paljoa kehittämisen tarvetta ei ole. Kuitenkin yritin antaa jotakin palautetta, josta saattaisi olla apua.

**Asioita, joita voisi muuttaa, lisätä tai kehittää:**
- Käyttöohjeissa voisi mainita virtuaaliympäristön luonnista ja ohjeiden terminaali komennot voisi muuttaa kopioitaviksi koodilohkoiksi
- Voisi estää sellaisten päivämäärien lisäämisen, jotka ovat menneisyydessä (esim 02.04.1999 toimii)
- Typen tarkoitus hieman epäselvä (ilmeisesti voidaan käyttää jaotteluun; jota ei olla implementoitu vielä)
- ToDo listan tomorrow-osion "No todos tomorrow!"-teksti kasautuu oudosti riippuen kaikkien ToDos määrästä, vaikka huomiselle olisikin olemassa jokin task (**kuva selkeyttää mitä tarkoitan**) 
![Screenshot from 2023-10-13 21-20-40](https://github.com/mcpaulafi/Todotoday/assets/72695556/31e5948d-7a83-4cd4-ad1f-da6838dae83a)

**Asioita, jotka ovat erinomaisella mallillaan:**
- Miellyttävä ja selkeä käyttöliittymä (sekä hyvin keskitetty) 
- Uutta käyttäjää luodessa sovellus varmistaa salasanan kahdesti ja ilmoittaa jos ne eroavat
- Näet kenenä olet kirjautunut sisään sekä pystyt kirjautumaan ulos
- ToDo list jaoiteltu kivasti päivien mukaan
- Monipuolinen tietokanta skeema
- Projektien ja tyyppien poisto on mahdollista sekä helppoa
- Väärillä tunnuksilla ei pysty kirjautumaan
- Samannimisiä käyttäjiä ei pysty luomaan
- On olemassa salasanojen ja käyttäjänimien minimi pituus niitä luodessa
- Parametrien käytön ansiosta SQL-injektio on torjuttu
- Koodi on selkeää ja siistiä
- Kommentit koodissa ovat hyviä
- XSS-haavoittuvuus estetty
- Dokumentointi on hyvässä jamassa

**Comment by mcpaulafi** [comment]
Kiitos huomioista. Nyt pitäisi olla kaikki kunnossa.
